backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "productos" # Used in routes, e.g., /admin/collections/blog
    label: "Productos" # Used in the UI
    folder: "src/info/information" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "title"}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Icono - Imagen", name: "icon", widget: "image"}
      - {label: "Imagen 1", name: "imageOne", widget: "image", required: false}
      - {label: "Ingredientes", name: "body", widget: "markdown"}
